export const ShopActionTypes = {
    UPDATE_COLLECTION_START : 'UPDATE_COLLECTION_START',
    UPDATE_COLLECTION_SUCCESS : 'UPDATE_COLLECTION_SUCCESS',
    UPDATE_COLLECTION_FAIL : 'UPDATE_COLLECTION_FAIL'
};