export const shopActionTypes = {
    ON_ITEMS_UPDATE : 'ON_ITEMS_UPDATE',
    UPDATE_COLLECTION_START : 'UPDATE_COLLECTION_START',
    UPDATE_COLLECTION_SUCCESS : 'UPDATE_COLLECTION_SUCCESS',
    UPDATE_COLLECTION_FAIL : 'UPDATE_COLLECTION_FAIL'
};