export const userActionTypes = {
    GOOGLE_START_SIGNIN : 'GOOGLE_START_SIGNIN',
    SIGNIN_SUCCESS : 'SIGNIN_SUCCESS',
    SIGNIN_FAIL : 'SIGNIN_FAIL',
    EMAIL_START_SIGNIN : 'EMAIL_START_SIGNIN',
    USER_SIGN_OUT_START : 'USER_SIGN_OUT_START',
    USER_SIGN_OUT_SUCCESS : 'USER_SIGN_OUT_SUCCESS',
    USER_SIGN_OUT_FAIL : 'USER_SIGN_OUT_FAIL',
    IS_USER_AUTHENTICATED : 'IS_USER_AUTHENTICATED'
};