export const userActionTypes = {

    SET_CURRENT_USER : 'SET_CURRENT_USER',
    GOOGLE_START_SIGNIN : 'GOOGLE_START_SIGNIN',
    GOOGLE_START_SIGNIN_SUCCESS : 'GOOGLE_START_SIGNIN_SUCCESS',
    GOOGLE_START_SIGNIN_FAIL : 'GOOGLE_START_SIGNIN_FAIL',
    EMAIL_START_SIGNIN : 'EMAIL_START_SIGNIN',
    EMAIL_START_SIGNIN_SUCCESS : 'EMAIL_START_SIGNIN_SUCCESS',
    EMAIL_START_SIGNIN_FAIL : 'EMAIL_START_SIGNIN_FAIL',
    USER_SIGN_OUT_START : 'USER_SIGN_OUT_START',
    USER_SIGN_OUT_SUCCESS : 'USER_SIGN_OUT_SUCCESS',
    USER_SIGN_OUT_FAIL : 'USER_SIGN_OUT_FAIL',

};